FROM php:8.3-apache

COPY src/ /var/www/src
COPY public/ /var/www/public

RUN apt-get update
RUN apt-get install -y git curl zip unzip 

RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-install sockets
COPY --from=composer /usr/bin/composer /usr/bin/composer

RUN a2enmod rewrite
RUN service apache2 restart

EXPOSE 80
EXPOSE 3306

CMD ["apache2-foreground"]
