version: '3.8'

services:
  distance_cep:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: DockerFile
    container_name: distance_cep
    image: distance-cep:1.0.0
    restart: always
    volumes:
      - ./src:/app/src
      - ./html:/app/html
    ports:
      - 8000:80
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    networks:
      - mynetwork
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

    links:
      - db

  db:
    image: mysql
    restart: always
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: lucas
      MYSQL_PASSWORD: lucas
      MYSQL_DATABASE: distance_cep
    ports:
      - '3306:3306'
    networks:
      - mynetwork
    extra_hosts:
      - "my-mysql-alias:127.0.0.1"
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 5s
        retries: 10
    

networks:
  mynetwork:
    driver: bridge