FROM distance-cep

COPY src/html /var/www/html
COPY src/ /app

RUN apt-get update
RUN apt-get install -y git curl zip unzip 

RUN docker-php-ext-install pdo_mysql
COPY --from=composer /usr/bin/composer /usr/bin/composer

RUN a2enmod rewrite
RUN service apache2 restart


WORKDIR /app

RUN composer install

EXPOSE 80

CMD ["apache2-foreground"]
